Stuff in a file 

YML stuff

It's like camel stuff but different
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$
:building_the_toolbelt_t2_2015 thoth$ sl
McLappy:building_the_toolbelt_t2_2015 thoth$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
McLappy:building_the_toolbelt_t2_2015 thoth$ rails -v
McLappy:building_the_toolbelt_t2_2015 thoth$
McLappy:building_the_toolbelt_t2_2015 thoth$ open files/toolbelt_syllabus_ts_t015.pdf
The file /Users/thoth/workspace/davinci_coders_t2_2015/building_the_toolbelt_t2_2015/files/tooMcLaMcMcMcLaMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcMcLappy:McLappy:building_the_toolbelt_t2_2015 thoth$ git pull
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 4), reused 1 (delta 1), pack-reused 4
Unpacking objects: 100% (17/17), done.
From github.com:davincicoders/building_the_toolbelt_t2_2015
   c5efc6d..b74f2e9  master     -> origin/master
Updating c5efc6d..b74f2e9
Fast-forward
 class_schedule.pdf                         | Bin 26281 -> 27776 bytes
 presentations/command_line_assignment.pptx | Bin 216392 -> 79339 bytes
 tracker_assignments/learn_command_line.csv | 242 ++++++++++++++++++++++++++
McLappy:building_the_toolbelt_t2_2015 thoth$